-- Create tables--

create table Fornecedor (
  cod_fornecedor number GENERATED BY DEFAULT AS IDENTITY,
  nome VARCHAR2(255) constraint nn_fornecedor_nome not null,
  morada VARCHAR2(255) constraint nn_fornecedor_morada not null,
  nif CHAR(9) UNIQUE constraint nn_fornecedor_nif not null,
  telefone CHAR(9) UNIQUE constraint nn_fornecedor_telefone not null,
  constraint pk_cod_fornecedor PRIMARY KEY (cod_fornecedor)
);

create table Produto(
  cod_produto number GENERATED BY DEFAULT AS IDENTITY,
  descricao VARCHAR2(255) constraint nn_produto_descricao not null,
  unidade_medida VARCHAR2(5) constraint nn_produto_unidade_medida not null,
  preco number(*,2) constraint ck_produto_preco check (preco > 0),
  constraint pk_cod_produto PRIMARY KEY (cod_produto)
);

create table FornecedorProduto (
  cod_fornecedor number references Fornecedor (cod_fornecedor),
  cod_produto number references Produto (cod_produto),
  preco_venda number(*,2) constraint ck_preco_venda check (preco_venda > 0),
  desconto number(*,2),
  constraint pk_fornecedor_produto PRIMARY KEY (cod_fornecedor, cod_produto)
);

create table Armazem (
  cod_armazem number GENERATED BY DEFAULT AS IDENTITY,
  nome VARCHAR2 (255) constraint nn_armazem_nome not null,
  morada VARCHAR2 (255) constraint nn_armazem_morada not null,
  cidade VARCHAR2 (255) constraint nn_armazem_cidade not null,
  constraint pk_cod_armazem PRIMARY KEY (cod_armazem)
);

create table Empregado (
 cod_empregado number GENERATED BY DEFAULT AS IDENTITY,
 cod_supervisor number references Empregado(cod_empregado) null,
 cod_armazem  number references Armazem(cod_armazem),
 nome VARCHAR2(255) constraint nn_empregado_nome not null,
 morada VARCHAR2(255) constraint nn_empregado_morada not null,
 salario_semanal number(*,2) constraint ck_salario_semanal check (salario_semanal > 0),
 formacao VARCHAR2(255) constraint nn_empregado_formacao not null,
 constraint pk_cod_empregado PRIMARY KEY (cod_empregado)
);

create table ArmazemProduto (
  cod_armazem number references Armazem(cod_armazem),
  cod_produto number references Produto(cod_produto),
  stock INTEGER constraint nn_stock not null,
  stock_minimo INTEGER constraint nn_stock_minimo not null,
  corredor INTEGER constraint nn_armazemProduto_corredor not null,
  prateleira INTEGER constraint nn_armazemProduto_prateleira not null,
  constraint ck_stock check (stock >= stock_minimo),
  constraint pk_armazem_produto PRIMARY KEY(cod_armazem, cod_produto)
);

create table OrdemCompra (
 nr_ordem number GENERATED BY DEFAULT AS IDENTITY,
 cod_fornecedor number references Fornecedor(cod_fornecedor),
 cod_empregado number references Empregado(cod_empregado),
 data_compra TIMESTAMP default systimestamp,
 valor_total number(*,2) constraint nn_valor_total not null,
 data_entrega TIMESTAMP,
 estado INTEGER default 1,
 constraint pk_nr_ordem PRIMARY KEY(nr_ordem),
 constraint ck_estado_dataEntrega check((estado = 2 AND data_entrega IS NULL)
            or (estado = 3 AND data_compra < data_entrega))
 );

create table OrdemCompraProduto (
 nr_ordem number references OrdemCompra(nr_ordem),
 linha number GENERATED BY DEFAULT AS IDENTITY,
 cod_produto number references Produto(cod_produto),
 quantidade_solicitada INTEGER,
 desconto_pedido number(*,2) constraint ck_desconto_pedido check (desconto_pedido >= 0),
 constraint ck_quantidade_solicitada check (quantidade_solicitada > 0),
 constraint pk_ordem_compra_produto PRIMARY KEY(nr_ordem, linha)
);
