-- Drop Table --
drop table ArmazemProduto CASCADE CONSTRAINTS PURGE;
drop table Pagamento CASCADE CONSTRAINTS PURGE;
drop table Incidente CASCADE CONSTRAINTS PURGE;
drop table TipoIncidente CASCADE CONSTRAINTS PURGE;
drop table Relatorio CASCADE CONSTRAINTS PURGE;
drop table Etapa CASCADE CONSTRAINTS PURGE;
drop table GuiaSaidaProduto CASCADE CONSTRAINTS PURGE;
drop table ProdutoZonaFisica CASCADE CONSTRAINTS PURGE;
drop table NotaEncomenda CASCADE CONSTRAINTS PURGE;
drop table GuiaTransporte CASCADE CONSTRAINTS PURGE;
drop table Viagem CASCADE CONSTRAINTS PURGE;
drop table Veiculo CASCADE CONSTRAINTS PURGE;
drop table Modelo CASCADE CONSTRAINTS PURGE;
drop table TipoVeiculo CASCADE CONSTRAINTS PURGE;
drop table Marca CASCADE CONSTRAINTS PURGE;
drop table Fatura CASCADE CONSTRAINTS PURGE;
drop table FielArmazem CASCADE CONSTRAINTS PURGE;
drop table Motorista CASCADE CONSTRAINTS PURGE;
drop table Vendedor CASCADE CONSTRAINTS PURGE;
drop table Funcionario CASCADE CONSTRAINTS PURGE;
drop table Cliente CASCADE CONSTRAINTS PURGE;
drop table TipoCliente CASCADE CONSTRAINTS PURGE;
drop table PrecoProduto CASCADE CONSTRAINTS PURGE;
drop table Produto CASCADE CONSTRAINTS PURGE;
drop table Unidade CASCADE CONSTRAINTS PURGE;
drop table ZonaFisica CASCADE CONSTRAINTS PURGE;
drop table Armazem CASCADE CONSTRAINTS PURGE;
drop table ZonaGeografica CASCADE CONSTRAINTS PURGE;

-- Create table --
CREATE TABLE ZonaGeografica (
  cod_zona  number GENERATED BY DEFAULT AS IDENTITY,
  descrição varchar2(255) NOT NULL,
  CONSTRAINT pk_zona PRIMARY KEY (cod_zona)
);

﻿CREATE TABLE Armazem (
  cod_armazem number GENERATED BY DEFAULT AS IDENTITY,
  cod_zona    number references ZonaGeografica(cod_zona),
  nome        varchar2(255) NOT NULL,
  morada      varchar2(255) NOT NULL,
  latitude    number(10, 8) NOT NULL,
  longitude   number(10, 8) NOT NULL,
  CONSTRAINT pk_armazem PRIMARY KEY (cod_armazem)
);

CREATE TABLE ZonaFisica (
  cod_zona_fisica number GENERATED BY DEFAULT AS IDENTITY,
  cod_armazem     number references Armazem(cod_armazem),
  volume_maximo   number(*, 2) NOT NULL,
  CONSTRAINT pk_zonaFisica PRIMARY KEY (cod_zona_fisica,
  cod_armazem)
);

CREATE TABLE Unidade (
  cod_unidade number GENERATED BY DEFAULT AS IDENTITY,
  descricao   varchar2(255) NOT NULL,
  constraint pk_unidade PRIMARY KEY (cod_unidade)
);

CREATE TABLE Produto (
  cod_produto number GENERATED BY DEFAULT AS IDENTITY,
  cod_unidade number references Unidade(cod_unidade),
  nome        varchar2(255) NOT NULL,
  descrição   varchar2(255) NOT NULL,
  peso        number(*,2),
  volume      number(*,2),
  constraint pk_produto PRIMARY KEY (cod_produto)
);

CREATE TABLE PrecoProduto (
  dataInicio   timestamp,
  cod_produto  number references Produto(cod_produto),
  precoVenda   number(*, 2) NOT NULL,
  preço_compra number(*, 2) NOT NULL,
  constraint pk_precoProduto PRIMARY KEY (dataInicio, cod_produto)
);

CREATE TABLE TipoCliente (
  cod_tipo      number GENERATED BY DEFAULT AS IDENTITY,
  descricao     varchar2(255) NOT NULL,
  volume_minimo number(*, 2),
  volume_maximo number(*, 2),
  constraint pk_tipoCliente PRIMARY KEY (cod_tipo)
);

CREATE TABLE Cliente (
  cod_cliente        number GENERATED BY DEFAULT AS IDENTITY,
  nome               varchar2(255) NOT NULL,
  morada             varchar2(255) NOT NULL,
  codigoPostal       char(8) NOT NULL,
  telemovel          char(9) NOT NULL,
  NIF                char(9) NOT NULL UNIQUE,
  cod_zonaGeografica number references ZonaGeografica(cod_zona),
  cod_tipo           number references TipoCliente(cod_tipo),
  data_atualizacao   timestamp,
  constraint pk_cliente PRIMARY KEY (cod_cliente)
);

CREATE TABLE Funcionario (
  cod_funcionario number GENERATED BY DEFAULT AS IDENTITY,
  cod_supervisor  number references Funcionario(cod_funcionario) null,
  cod_armazem     number references Armazem(cod_armazem),
  nome            varchar2(255) NOT NULL,
  cartaoCidadao   char(8) NOT NULL UNIQUE,
  NIF             char(9) NOT NULL UNIQUE,
  morada          varchar2(255) NOT NULL,
  data_nascimento timestamp NOT NULL,
  salario         number(*,2) NOT NULL,
  categoria       varchar2(255) NOT NULL,
  constraint pk_funcionario PRIMARY KEY (cod_funcionario)
);

CREATE TABLE Vendedor (
  cod_funcionario number references Funcionario(cod_funcionario),
  constraint pk_vendedor PRIMARY KEY (cod_funcionario)
);

CREATE TABLE Motorista (
  cod_funcionario number references Funcionario(cod_funcionario),
  constraint pk_motorista PRIMARY KEY (cod_funcionario)
);

CREATE TABLE FielArmazem (
  cod_funcionario number references Funcionario(cod_funcionario),
  constraint pk_fielArmazem PRIMARY KEY (cod_funcionario)
);

CREATE TABLE Fatura (
  nr_fatura      number GENERATED BY DEFAULT AS IDENTITY,
  cod_cliente    number references Cliente (cod_cliente),
  cod_vendedor   number references Vendedor (cod_funcionario),
  data_emissao   timestamp NOT NULL,
  preco_base     number(*, 2) NOT NULL,
  valor_IVA      number(*, 2) NOT NULL,
  valor_desconto number(*, 2),
  constraint pk_fatura PRIMARY KEY (nr_fatura)
);

CREATE TABLE Marca (
  cod_marca  number GENERATED BY DEFAULT AS IDENTITY,
  nome_marca varchar2(255) NOT NULL,
  constraint pk_marca PRIMARY KEY (cod_marca)
);

CREATE TABLE TipoVeiculo (
  cod_tipo_veiculo number GENERATED BY DEFAULT AS IDENTITY,
  numero_eixos     number(10) NOT NULL,
  constraint pk_tipoVeiculo PRIMARY KEY (cod_tipo_veiculo)
);

CREATE TABLE Modelo (
  cod_modelo       number GENERATED BY DEFAULT AS IDENTITY,
  cod_marca        number references Marca(cod_marca),
  cod_tipo_veiculo number references TipoVeiculo(cod_tipo_veiculo),
  nome_modelo      varchar2(255) NOT NULL,
  peso_maximo      number(*, 2) NOT NULL,
  volume_maximo    number(*, 2) NOT NULL,
  constraint pk_modelo PRIMARY KEY (cod_modelo,
  cod_marca)
);

CREATE TABLE Veiculo (
  matricula      char(8) NOT NULL,
  cod_modelo     number references Modelo(cod_modelo),
  cod_marca      number references Marca(cod_marca),
  apolice_seguro number(10) NOT NULL,
  kilometragem   number(10) NOT NULL,
  estado_servico number(10) NOT NULL,
  constraint pk_veiculo PRIMARY KEY (matricula)
);

CREATE TABLE Viagem (
  cod_viagem     number GENERATED BY DEFAULT AS IDENTITY,
  cod_motorista  number references Motorista(cod_funcionario),
  matricula      char(8) references Veiculo(matricula),
  data           timestamp NOT NULL,
  peso_ocupado   number(*, 2) NOT NULL,
  volume_ocupado number(*, 2) NOT NULL,
  constraint pk_viagem PRIMARY KEY (cod_viagem)
);

CREATE TABLE GuiaTransporte (
  cod_guia_transporte number GENERATED BY DEFAULT AS IDENTITY,
  cod_viagem          number references Viagem(cod_viagem),
  constraint pk_guiaTransport PRIMARY KEY (cod_guia_transporte)
);

CREATE TABLE NotaEncomenda (
  cod_nota_encomenda  number GENERATED BY DEFAULT AS IDENTITY,
  nr_fatura           number references Fatura(nr_fatura),
  cod_cliente         number references Cliente(cod_cliente),
  cod_vendedor        number references Vendedor(cod_funcionario),
  cod_fiel_armazem    number references FielArmazem(cod_funcionario),
  cod_guia_transporte number references GuiaTransporte(cod_guia_transporte),
  data                timestamp NOT NULL,
  estado              number(1) NOT NULL,
  constraint pk_nota_encomenda PRIMARY KEY (cod_nota_encomenda));

CREATE TABLE ProdutoZonaFisica (
    cod_produto     number references Produto(cod_produto),
    cod_zona_fisica number references ZonaFisica(cod_zona_fisica),
    cod_armazem     number references ZonaFisica(cod_armazem),
    corredor        number(10),
    prateleira      number(10),
    stock           number(10),
    constraint pk_produto_zonaFisica PRIMARY KEY (cod_produto, cod_zona_fisica, cod_armazem)
  );

CREATE TABLE GuiaSaidaProduto (
  linha               number GENERATED BY DEFAULT AS IDENTITY,
  cod_produto         number references ProdutoZonaFisica(cod_produto),
  cod_zona_fisica     number references ProdutoZonaFisica(cod_zona_fisica),
  cod_armazem         number references ProdutoZonaFisica(cod_armazem),
  cod_nota_encomenda  number references NotaEncomenda(cod_nota_encomenda),
  cod_guia_transporte number references GuiaTransporte(cod_guia_transporte),
  quantidade          number(10) NOT NULL,
  constraint pk_guia_saida_produto PRIMARY KEY (linha)
);

CREATE TABLE Etapa (
  nr_etapa            number GENERATED BY DEFAULT AS IDENTITY,
  cod_cliente_inicial number references Cliente(cod_cliente_inicial),
  cod_cliente_final   number references Cliente(cod_cliente_final),
  cod_viagem          number references Viagem(cod_viagem),
  constraint pk_etapa PRIMARY KEY (nr_etapa)
);

CREATE TABLE Relatorio (
  cod_relatorio number GENERATED BY DEFAULT AS IDENTITY,
  cod_viagem    number references Viagem(cod_viagem),
  constraint pk_relatorio PRIMARY KEY (cod_relatorio)
);

CREATE TABLE TipoIncidente (
  cod_tipo_incidente number GENERATED BY DEFAULT AS IDENTITY,
  descricao          nvarchar2(255) NOT NULL,
  PRIMARY KEY (cod_tipo_incidente));

CREATE TABLE Incidente (
  cod_incidente      number GENERATED BY DEFAULT AS IDENTITY,
  cod_tipo_incidente number references TipoIncidente(cod_tipo_incidente),
  nr_etapa           number references Etapa(nr_etapa),
  nr_viagem          number references Etapa(nr_viagem),
  constraint pk_incidente PRIMARY KEY (cod_incidente)
);

CREATE TABLE Pagamento (
  cod_pagamento number GENERATED BY DEFAULT AS IDENTITY,
  cod_cliente   number references Cliente(cod_cliente),
  nr_fatura     number references Fatura(nr_fatura),
  data          timestamp NOT NULL,
  valor         number(*, 2) NOT NULL,
  constraint pk_pagamento PRIMARY KEY (cod_pagamento));

CREATE TABLE ArmazemProduto (
  cod_produto  number references Produto(cod_produto),
  stock_minimo number(*, 2),
  cod_armazem  number references Armazem(cod_armazem),
  constraint pk_armazemProduto PRIMARY KEY (cod_produto,
  cod_armazem)
);
